NovelWeb_SS5/Controllers/CrudCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NovelWeb_SS5.Models;

namespace NovelWeb_SS5.Controllers
{
    public class CrudCommentsController : Controller
    {
        private DbModelsNovelWeb db = new DbModelsNovelWeb();

        // GET: CrudComments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Chuong).Include(c => c.User);
            return View(comments.ToList());
        }

        // GET: CrudComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: CrudComments/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: CrudComments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.idChuong = new SelectList(db.Chuongs, "idChuong", "soChuong", comment.idChuong);
            ViewBag.idUser = new SelectList(db.Users, "idUser", "userName", comment.idUser);
            return View(comment);
        }

        // POST: CrudComments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idCmt,noiDungcmt,ngay,userName,idChuong,idUser")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idChuong = new SelectList(db.Chuongs, "idChuong", "soChuong", comment.idChuong);
            ViewBag.idUser = new SelectList(db.Users, "idUser", "userName", comment.idUser);
            return View(comment);
        }

        // GET: CrudComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: CrudComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index_Admin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Index_Admin()
        {
            List<Comment> cmt = db.Comments.ToList();
            return View(cmt);
        }

        public ActionResult PostComment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PostComment(string CommentText)
        {
            int userID = Convert.ToInt32(Session["UserId"]);
            if (userID == 0)
            {
                return RedirectToAction("IndexUser", "LoginUser");
            }

            Comment c = new Comment();
            c.noiDungcmt = CommentText;
            c.ngay = DateTime.Now;
            c.idUser = userID;
            db.Comments.Add(c);
            db.SaveChanges();
            return RedirectToAction("Index_Admin");
        }

        public ActionResult PostReply()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PostReply(string CommentText)
        {
            int userID = Convert.ToInt32(Session["UserId"]);
            string userName = Convert.ToString(Session["UserName"]);
            Comment c = new Comment();
            c.noiDungcmt = CommentText;
            c.ngay = DateTime.Now;

            c.userName = userName;
            db.Comments.Add(c);
            db.SaveChanges();
            return RedirectToAction("Index_Admin");
        }
    }
}

NovelWeb_SS5/Views/CrudComments/Delete.cshtml
@model NovelWeb_SS5.Models.Comment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Xóa comment này?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span>Nội dung comment</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noiDungcmt)
        </dd>

        <dt>
            <span>Thời gian</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay)
        </dd>

        <dt>
            <span>User comment</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userName)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.User.userName)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NovelWeb_SS5/Views/CrudComments/Details.cshtml
@model NovelWeb_SS5.Models.Comment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noiDungcmt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noiDungcmt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Chuong.soChuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chuong.soChuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.userName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.userName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idCmt }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NovelWeb_SS5/Views/CrudComments/Edit.cshtml
@model NovelWeb_SS5.Models.Comment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Comment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idCmt)

        <div class="form-group">
            @Html.LabelFor(model => model.noiDungcmt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.noiDungcmt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noiDungcmt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idChuong, "idChuong", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idChuong", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idChuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idUser, "idUser", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idUser", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NovelWeb_SS5/Views/CrudComments/Index_Admin.cshtml
@model IEnumerable<NovelWeb_SS5.Models.Comment>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2 class="text-success text-center">Chat Room</h2>

<link href="~/Content/bootstrap-readable.css" rel="stylesheet" />
<table class="table table-hover">

    @foreach (var item in Model)
    {
        <tr>
            <td class=" text-center">

                <span style="margin-right:16px; color:darkslategrey; font-size:17px"> @item.userName:  </span>
                <span style="font-size:20px"> @Html.DisplayFor(modelItem => item.noiDungcmt)</span>
                <span style="margin-left:20px; font-size:14px">  @Html.DisplayFor(modelItem => item.ngay)</span>
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.idCmt })
            </td>
        </tr>
    }

    <tr>
        <td>

            @using (Html.BeginForm("PostReply", "CrudComments", FormMethod.Post))
            {
                if (Session["UserId"] != null && Session["UserName"] != null)
                {
                    <input placeholder="Gõ gì đó.." type="text" class="form-control" name="CommentText" style="width:100%; height:60px; font-size:20px; margin-top:10px" />
                    <br />
                    <button type="submit" value="Okay" class="btn btn-success" style="margin-top:10px;">Send </button>

                }

            }
        </td>
    </tr>
</table>