NovelWeb_SS5/Controllers/HomeTruyensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NovelWeb_SS5.Models;
using PagedList;

namespace NovelWeb_SS5.Controllers
{
    public class HomeTruyensController : Controller
    {
        private DbModelsNovelWeb db = new DbModelsNovelWeb();

        // GET: HomeTruyens

        // GET: Admin/Truyens
        public ActionResult Index()
        {
            List<Truyen> truyens = db.Truyens.Include(t => t.TheLoai).ToList();

            return View(truyens);
        }

        public ActionResult TruyenDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Truyen truyen = db.Truyens.Find(id);
            if (truyen == null)
            {
                return HttpNotFound();
            }
            return View(truyen);
        }

        public ActionResult DanhSachChuong(int id)
        {
            DbModelsNovelWeb context = new DbModelsNovelWeb();

            List<Chuong> chuongs = context.Chuongs.ToList();
            var q = from x in chuongs
                    where x.idTruyen == id
                    select x;

            return PartialView(q);
        }

        public ActionResult ChiTietChuong(int id)
        {
            DbModelsNovelWeb context = new DbModelsNovelWeb();

            Chuong chuong = context.Chuongs.FirstOrDefault(x => x.idChuong == id);

            return PartialView(chuong);
        }

        //Tro toi chuong moi + 1
        public ActionResult ChiTietChuongNext(int id)
        {
            DbModelsNovelWeb context = new DbModelsNovelWeb();

            Chuong chuong = context.Chuongs.FirstOrDefault(x => x.idChuong == id + 1);

            return PartialView(chuong);
        }

        public ActionResult PageListTruyen(int page = 1, int pageSize = 2)
        {
            List<Truyen> truyens = db.Truyens.ToList();
            PagedList<Truyen> model = new PagedList<Truyen>(truyens, page, pageSize);
            return View(model);
        }

        public List<Truyen> TruyenMoi(int count)
        {
            return db.Truyens.OrderByDescending(a => a.ngayDang).Take(count).ToList();
        }

        public ActionResult TruyenMoiNhat()
        {
            var truyenmoi = TruyenMoi(4);
            return PartialView(truyenmoi);
        }

        [ChildActionOnly]
        public ActionResult TheLoai()
        {
            List<TheLoai> theloais = db.TheLoais.ToList();
            return PartialView(theloais);
        }

        public ActionResult TruyenTheoTheLoai(int id)
        {
            List<Truyen> truyens = db.Truyens.Where(x => x.idTL == id).ToList();
            return View(truyens);
        }

        public ActionResult SaveTruyens(int idTruyen)
        {
            var savetruyen = new List<Truyen>();
            var truyen = db.Truyens.Find(idTruyen);

            savetruyen.Add(new Truyen()
            {
                tenTruyen = truyen.tenTruyen
            ,
                idTruyen = truyen.idTruyen
            });
            Session["truyenn"] = savetruyen;
            return View();
        }

        public List<Truyen> TruyenXN(int count)
        {
            return db.Truyens.OrderBy(a => a.ngayDang).ThenBy(a => a.idTruyen).Take(count).ToList();
        }

        public ActionResult TruyenXemNhieu()
        {
            var truyenmoi1 = TruyenXN(4);
            return PartialView(truyenmoi1);
        }

        public ActionResult XemNgay(int id)
        {
            Chuong chuongs = db.Chuongs.FirstOrDefault(a => a.idChuong == id);

            return RedirectToAction("ChiTietChuong");
        }

        //Xem ham nayyy

        public ActionResult Sorting(string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var truyens = from s in db.Truyens
                          select s;
            switch (sortOrder)
            {
                case "name_desc":
                    truyens = truyens.OrderByDescending(s => s.idTruyen);
                    break;

                case "Date":
                    truyens = truyens.OrderBy(s => s.ngayDang);
                    break;

                case "date_desc":
                    truyens = truyens.OrderByDescending(s => s.ngayDang);
                    break;

                default:
                    truyens = truyens.OrderBy(s => s.idTruyen);
                    break;
            }
            return View(truyens.ToList());
        }

        public ActionResult UserSearchTruyens(string searching)
        {
            List<Truyen> truyens = db.Truyens
               .Where(x => x.tenTruyen.Contains(searching) | searching == null)
               .ToList();

            return PartialView(truyens);
        }

        public ActionResult BreadCrumb(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Truyen truyen = db.Truyens.Find(id);
            if (truyen == null)
            {
                return HttpNotFound();
            }
            return PartialView(truyen);
        }

        public ActionResult Titlesectiontitle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheLoai theLoai = db.TheLoais.Find(id);
            if (theLoai == null)
            {
                return HttpNotFound();
            }
            return PartialView(theLoai);
        }

        public ActionResult BreadcrumbCate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheLoai theLoai = db.TheLoais.Find(id);
            if (theLoai == null)
            {
                return HttpNotFound();
            }
            return PartialView(theLoai);
        }
    }
}

NovelWeb_SS5/Controllers/LoginUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NovelWeb_SS5.Models;

namespace NovelWeb_SS5.Controllers
{
    public class LoginUserController : Controller
    {
        // GET: LoginUser
        private DbModelsNovelWeb db = new DbModelsNovelWeb();

        // GET: Admin/Login
        public ActionResult IndexUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Authorise_User(User user)
        {
            if (ModelState.IsValid)
            {
                var userDetail = db.Users
                .Where(x => x.userName == user.userName && x.passWord == user.passWord)
                .FirstOrDefault();

                if (userDetail == null)
                {
                    ViewBag.ErrorMessage = "Sai tài khoản hoặc mật khẩu";

                    return View("IndexUser", user);
                }
                else if (userDetail != null && userDetail.idQuyen == 1)
                {
                    Session["UserId"] = user.idUser;
                    Session["UserName"] = user.userName;
                    Session["UserHoTen"] = user.hoTen;
                    return RedirectToAction("Index_Admin", "CrudComments");
                }
                else
                {
                    Session["UserId"] = user.idUser;
                    Session["UserName"] = user.userName;
                    Session["UserHoTen"] = user.hoTen;
                    return RedirectToAction("Index", "Comment");
                }
            }
            else
            {
                ViewBag.error = "Đăng nhập thất bại, sai tài khoản hoặc mật khẩu";
                return View("IndexUser", user);
            }
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }

        public ActionResult CreateUser()
        {
            return View();
        }

        // POST: Admin/CrudUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUser([Bind(Include = "idUser,userName,passWord,hoTen")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("IndexUser");
            }

            return View(user);
        }
    }
}

NovelWeb_SS5/Views/Shared/BreadCrumb.cshtml
@model NovelWeb_SS5.Models.Truyen

<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="@Url.Action("Index","HomeTruyens")"><i class="fa fa-home"></i> Home</a>
                    <a href="@Url.Action("Index","HomeTruyens")">Categories</a>

                    <a href="#">@Html.DisplayFor(x => x.TheLoai.tenLoai)</a>
                </div>
            </div>
        </div>
    </div>
</div>

NovelWeb_SS5/Views/Shared/Cate.cshtml
@model IEnumerable<NovelWeb_SS5.Models.Truyen>

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Novel Web</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/plyr.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/style.css" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="./index.html">
                            <img src="img/logo.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="@Url.Action("Index", "HomeTruyens")">Homepage</a></li>
                                <li>

                                    @{
                                        Html.RenderAction("TheLoai", "HomeTruyens");
                                    }
                                </li>
                                <li><a href="@Url.Action("IndexUser","LoginUser")">Room Chat</a></li>
                                <li><a href="#">Contacts</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="#" class="search-switch"><span class="icon_search"></span></a>
                        <a href="./login.html"><span class="icon_profile"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->
    <!-- Breadcrumb Begin -->
    @{

        Html.RenderAction("BreadcrumbCate", "HomeTruyens");
    }
    <!-- Breadcrumb End -->
    <!-- Product Section Begin -->
    <section class="product-page spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="product__page__content">
                        <div class="product__page__title">
                            <div class="row">
                                @{
                                    Html.RenderAction("Titlesectiontitle", "HomeTruyens");
                                }
                                <div class="col-lg-4 col-md-4 col-sm-6">
                                    <div class="product__page__filter">
                                        <p>Order by:</p>
                                        <select>
                                            <option value="">A-Z</option>
                                            <option value="">1-10</option>
                                            <option value="">10-50</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">

                            @RenderBody()

                            <div class="product__pagination">
                                <a href="#" class="current-page">1</a>
                                <a href="#">2</a>
                                <a href="#">3</a>
                                <a href="#">4</a>
                                <a href="#">5</a>
                                <a href="#"><i class="fa fa-angle-double-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Section End -->
    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="./index.html"><img src="img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="@Url.Action("Index","HomeTruyens")">Homepage</a></li>
                            <li><a href="@Url.Action("Index","HomeTruyens")">Categories</a></li>
                            <li><a href="@Url.Action("IndexUser","LoginUser")">Room Chat</a></li>
                            <li><a href="#">Contacts</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Search model Begin -->
    @*@{ Html.RenderAction("UserSearchTruyens", "HomeTruyens"); }*@

    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            @using (Html.BeginForm("UserSearchTruyens", "HomeTruyens", FormMethod.Get, new { @class = "search-model-form", @placeholder = "Search for..." }))
            {

                @Html.Editor("searching", "",
                    new
                    {
                        @id = "search-input",
                        @placeholder = "Search for...",
                        @type = "text"
                    })}
        </div>
    </div>
    <!-- Search model end -->
    <!-- Js Plugins -->
    <script src="~/Content/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/player.js"></script>
    <script src="~/Content/js/jquery.nice-select.min.js"></script>
    <script src="~/Content/js/mixitup.min.js"></script>
    <script src="~/Content/js/jquery.slicknav.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/main.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

NovelWeb_SS5/Views/Shared/DetailsTruyens.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Novel Web</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/plyr.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/Content/css/style.css" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="@Url.Action("Index","HomeTruyens")">
                            <!--<img style="width:60px; height:60px"--> @*src="~/Content/images/logo.png"*@ <!--alt="">-->
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="@Url.Action("Index","HomeTruyens")">Homepage</a></li>
                                @{ Html.RenderAction("TheLoai", "HomeTruyens"); }
                                <li><a href="@Url.Action("IndexUser","LoginUser")">Room Chat</a></li>
                                <li><a href="#">Contacts</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="#" class="search-switch"><span class="icon_search"></span></a>
                        <a href="@Url.Action("Index","Login", new { area = "Admin"})"><span class="icon_profile"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->
    <!-- Breadcrumb Begin -->
    @{ Html.RenderAction("BreadCrumb", "HomeTruyens"); }
    <!-- Breadcrumb End -->
    <!-- Anime Section Begin -->
    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                    @RenderBody()
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <div class="anime__details__review">
                        <div class="section-title">
                            <h5>Reviews</h5>
                        </div>
                        <div class="anime__review__item">
                            <div class="anime__review__item__pic">
                                <img src="img/anime/review-1.jpg" alt="">
                            </div>
                            <div class="anime__review__item__text">
                                <h6>Chris Curry - <span>1 Hour ago</span></h6>
                                <p>
                                    whachikan Just noticed that someone categorized this as belonging to the genre
                                    "demons" LOL
                                </p>
                            </div>
                        </div>
                        <div class="anime__review__item">
                            <div class="anime__review__item__pic">
                                <img src="img/anime/review-2.jpg" alt="">
                            </div>
                            <div class="anime__review__item__text">
                                <h6>Lewis Mann - <span>5 Hour ago</span></h6>
                                <p>Finally it came out ages ago</p>
                            </div>
                        </div>
                        <div class="anime__review__item">
                            <div class="anime__review__item__pic">
                                <img src="img/anime/review-3.jpg" alt="">
                            </div>
                            <div class="anime__review__item__text">
                                <h6>Louis Tyler - <span>20 Hour ago</span></h6>
                                <p>Where is the episode 15 ? Slow update! Tch</p>
                            </div>
                        </div>
                        <div class="anime__review__item">
                            <div class="anime__review__item__pic">
                                <img src="img/anime/review-4.jpg" alt="">
                            </div>
                            <div class="anime__review__item__text">
                                <h6>Chris Curry - <span>1 Hour ago</span></h6>
                                <p>
                                    whachikan Just noticed that someone categorized this as belonging to the genre
                                    "demons" LOL
                                </p>
                            </div>
                        </div>
                        <div class="anime__review__item">
                            <div class="anime__review__item__pic">
                                <img src="img/anime/review-5.jpg" alt="">
                            </div>
                            <div class="anime__review__item__text">
                                <h6>Lewis Mann - <span>5 Hour ago</span></h6>
                                <p>Finally it came out ages ago</p>
                            </div>
                        </div>
                        <div class="anime__review__item">
                            <div class="anime__review__item__pic">
                                <img src="img/anime/review-6.jpg" alt="">
                            </div>
                            <div class="anime__review__item__text">
                                <h6>Louis Tyler - <span>20 Hour ago</span></h6>
                                <p>Where is the episode 15 ? Slow update! Tch</p>
                            </div>
                        </div>
                    </div>
                    <div class="anime__details__form">
                        <div class="section-title">
                            <h5>Your Comment</h5>
                        </div>
                        <form action="#">
                            <textarea placeholder="Your Comment"></textarea>
                            <button type="submit"><i class="fa fa-location-arrow"></i> Review</button>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="anime__details__sidebar">
                        <div class="section-title">
                        </div>
                        @{ Html.RenderAction("TruyenXemNhieu", "HomeTruyens"); }
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Anime Section End -->
    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="./index.html"><img src="img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="./index.html">Homepage</a></li>
                            <li><a href="./categories.html">Categories</a></li>
                            <li><a href="./blog.html">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            @using (Html.BeginForm("UserSearchTruyens", "HomeTruyens", FormMethod.Get, new { @class = "search-model-form", @placeholder = "Search for..." }))
            {

@Html.Editor("searching", "",
        new
        {
            @id = "search-input",
            @placeholder = "Search for...",
            @type = "text"
        })}
        </div>
    </div>
    <!-- Search model end -->
    <!-- Js Plugins -->
    <script src="~/Content/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/player.js"></script>
    <script src="~/Content/js/jquery.nice-select.min.js"></script>
    <script src="~/Content/js/mixitup.min.js"></script>
    <script src="~/Content/js/jquery.slicknav.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/main.js"></script>
</body>
</html>

NovelWeb_SS5/Views/Shared/ProductItem.cshtml
<div class="col-lg-4 col-md-6 col-sm-6">
    <div class="product__item">
        <div class="product__item__pic set-bg" data-setbg="img/trending/trend-1.jpg">
            <div class="ep">18 / 18</div>
            <div class="comment"><i class="fa fa-comments"></i> 11</div>
            <div class="view"><i class="fa fa-eye"></i> 9141</div>
        </div>
        <div class="product__item__text">
            <ul>
                <li>Active</li>
                <li>Movie</li>
            </ul>
            <h5><a href="#">The Seven Deadly Sins: Wrath of the Gods</a></h5>
        </div>
    </div>
</div>

NovelWeb_SS5/Views/Shared/_HomeTruyens.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="img-fluid">
        <img src="~/Content/images/pixels5.png" />
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @RenderPage("_NavBarTop.cshtml")
        </div>
    </div>

    <div class="container">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - Novel Web</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NovelWeb_SS5/Views/Shared/_HomeTruyensDetails.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @RenderPage("_NavBarTop.cshtml")
        </div>
    </div>

    <div class="container">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - Novel Web</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NovelWeb_SS5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title RoomChat</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Room Chat</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NovelWeb_SS5/Views/Shared/_NavBarTop.cshtml
<nav class="navbar-static-top navbar-light">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href=" @Url.Action("Index", "HomeTruyens")"><img style="width:60px; height: 60px" src="~/Content/images/logo.png" /> </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                @{
                    Html.RenderAction("TheLoai", "HomeTruyens");

                }
            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
            </ul>
        </div>
    </div>
</nav>